AllCops:
  Exclude:
    - db/schema.rb
    - vendor/**/*
    - bin/**/*

Bundler/OrderedGems:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/AbcSize:
  Exclude:
    - db/migrate/*

Metrics/BlockLength:
  Exclude:
    - test/**/*

Metrics/ClassLength:
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Max: 15
  Exclude:
    - db/migrate/*

Lint/AmbiguousRegexpLiteral:
  Enabled: false
