language: ruby
cache: bundler
sudo: false
bundler_args: --path vendor --local --without development
before_script:
  - echo -e "Host wic.oweb.co\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - RUN_COVERAGE=travis bundle exec rake test
  - bundle exec rake coverage:report
deploy:
  - provider: script
    script: .travis/deploy_stage.sh
    on:
      branch: develop
      repo: Women-in-Computing-at-RIT/wichacks.io
  - provider: script
    script: .travis/deploy_prod.sh
    on:
      branch: master
      repo: Women-in-Computing-at-RIT/wichacks.io
addons:
  code_climate:
    repo_token: c377cc636e3f10276b52d937c1731f3fb693e7fea35bea2322bddafd55fe5261
