language: ruby
cache: bundler
sudo: false
bundler_args: --path vendor --local --without development
env:
  - DATABASE_URL="mysql2://travis@localhost/myapp_test"
before_script:
  - mysql -u root -e "CREATE DATABASE myapp_test;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON myapp_test.* TO 'travis'@'%';";
  - mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root mysql
  - echo -e "Host wic.oweb.co\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
script:
  - bundle exec rake db:migrate db:test:prepare
  - RUN_COVERAGE=travis bundle exec rake test
  - bundle exec rake coverage:report
deploy:
  - provider: script
    script: .travis/deploy_stage.sh
    on:
      branch: develop
      repo: Women-in-Computing-at-RIT/wichacks.io
  - provider: script
    script: .travis/deploy_prod.sh
    on:
      branch: master
      repo: Women-in-Computing-at-RIT/wichacks.io
addons:
  code_climate:
    repo_token: c377cc636e3f10276b52d937c1731f3fb693e7fea35bea2322bddafd55fe5261
