defaults: &defaults
  # Logic config
  registration_is_open: true
  event_is_over: false
  last_day_to_apply: <%= Date.new(2018, 2, 11) %>
  auto_late_waitlist: false

  # Content config
  name: WiCHacks
  logo_asset: wic-hacks-logo-white.png
  agreement_pdf_asset: "WiCHacks Agreement to Participate.pdf"
  email_from: '"WiCHacks" <hello@wichacks.io>'
  default_page_title: WiCHacks

  disclaimer: |
    **Applicants must be 18 years of age by February 11th.**
    This may change if we have additional space available. If interested, please sign up [here](https://goo.gl/forms/kUCPPoZndu9iBmgf1) to be notified instead!
  thanks_for_applying: |
    Thanks for applying! You will be notified of your acceptance via email in January.

development:
  <<: *defaults

test: &test
  <<: *defaults
  last_day_to_apply: <%= 2.months.from_now %>

production:
  <<: *defaults

staging:
  <<: *defaults
