defaults: &defaults
  # Logic config
  registration_is_open: false
  event_is_over: false
  last_day_to_apply: <%= Date.new(2019, 2, 1) %>
  event_start_date: <%= Date.new(2019, 3, 2) %>
  auto_late_waitlist: true

  # Content config
  name: WiCHacks
  logo_asset: wic-hacks-logo-white.png
  # favicon_asset: favicon.ico
  agreement_pdf_asset: "WiCHacks Agreement to Participate.pdf"
  email_from: '"WiCHacks" <hello@wichacks.io>'
  default_page_title: WiCHacks

  disabled_fields:
    - why_attend
  # disclaimer: |
  #   Foo bar
  thanks_for_applying: |
    Thanks for applying! You will be notified of your acceptance via email in January.

development:
  <<: *defaults

test: &test
  <<: *defaults
  last_day_to_apply: <%= 2.months.from_now %>

production:
  <<: *defaults

staging:
  <<: *defaults
