defaults: &defaults
  # Logic config
  registration_is_open: true
  event_is_over: false
  last_day_to_apply: <%= Date.new(2017, 2, 11) %>
  auto_late_waitlist: false

  # Content config
  name: WiCHacks
  logo_asset: wic-hacks-logo.png
  agreement_pdf_asset: wic-logo.png
  email_from: '"WiCHacks" <hello@wichacks.io>'
  default_page_title: WiCHacks

development:
  <<: *defaults

test: &test
  <<: *defaults
  last_day_to_apply: <%= 2.months.from_now %>

production:
  <<: *defaults

staging:
  <<: *defaults
